Implement Persistent Workers as an execution path
bazelbuild/bazel-buildfarm pull request #1260
Opened 2023-02-01 00:35 UTC by wiwa

Followup to #1195 

Add a new execution pathway in `worker/Executor.java` to use persistent workers via `PersistentExecutor`, like `DockerExecutor`.

Co-authored-by: Shane Delmore [shane@delmore.io](mailto:shane@delmore.io)

2023-08-14 03:36 UTC, werkt commented
@wiwa any chance this will get updated? I'd love to see this in, and could pick up the mantle if you don't have any time for it.

2023-10-11 20:10 UTC, wiwa commented
@werkt  Sorry, didn't see your comment! I'm mostly worried about test cases for this. I'll take a look this weekend again. Maybe I should just add a basic test case first and start from there.

2023-10-17 22:06 UTC, ShaneDelmore commented
@werkt We added some tests today, will come back and continue adding more tests in the following weeks.

2023-11-14 22:38 UTC, werkt requested changes
New files need some copyrights, and a buildifier run should fix most of it.

2023-11-14 22:38 UTC, werkt commented on src/main/java/build/buildfarm/worker/persistent/ProtoCoordinator.java
> +    e.printStackTrace();
send this to the logger with `log` method

2023-11-14 22:38 UTC, werkt commented on src/main/java/build/buildfarm/worker/persistent/WorkerInputs.java
> +  private static final Logger logger = Logger.getLogger(WorkerInputs.class.getName());
`@Log` this

2023-11-14 22:38 UTC, werkt commented on src/main/java/build/buildfarm/worker/persistent/WorkerInputs.java
> +    System.out.println(inputsDebugMsg);
debug print?

2023-11-14 22:38 UTC, werkt commented on src/main/java/build/buildfarm/worker/util/BUILD
> +        "//persistentworkers/src/main/protobuf:worker_protocol_java_proto",
alpha

2023-11-14 22:38 UTC, werkt commented on src/test/java/build/buildfarm/instance/shard/JedisCasWorkerMapTest.java
> -
ws

2023-11-14 22:38 UTC, werkt commented on src/test/java/build/buildfarm/worker/persistent/BUILD
> +        "//persistentworkers/src/main/protobuf:worker_protocol_java_proto",
alpha

2023-11-19 04:29 UTC, wiwa commented on src/main/java/build/buildfarm/worker/BUILD
> +        "//persistentworkers/src/main/java/persistent/common:persistent-common",
These are in fact sorted already (`//persistentworkers/...` before `//src/...`).

2023-11-19 04:30 UTC, wiwa commented on src/main/java/build/buildfarm/common/config/DequeueMatchSettings.java
> -
Unfortunately, this ws change (and the other one) are both from running `./.bazelci/format.sh` (on my WSL box).

2023-11-19 04:32 UTC, wiwa commented on src/main/java/build/buildfarm/worker/persistent/PersistentExecutor.java
> +    }
I'll put a comment (and "TODO" lol) up top:
```
// I believe the reason has to do with JavaBuilder workers not relying on env vars,
// as compared to rules_scala, only reading info from the argslist of each command.
// That would mean the Java worker keys should be invariant to the env vars we see.
```

2023-11-19 05:42 UTC, wiwa commented on src/main/java/build/buildfarm/worker/persistent/BUILD
> +        "//src/main/java/build/buildfarm/worker/util",
sorted

2023-11-19 07:58 UTC, wiwa commented
@ShaneDelmore I was testing this out with the current `bazel` (`6.4.0`) which now supports the `--experimental_remote_mark_tool_inputs` flag. It turns out we'll need to add `persistentWorkerKey` to the worker config (`config/Worker.java`), specifically allowing `DequeueMatchSettings` to accept `persistentWorkerKey`, which used to work as just a platform property `persistentWorkerKey: *`. We also need to figure out how to pass the worker init command from `bazel` (i.e. `persistentWorkerCommand`) -- this should be a small modification to `bazel` itself. Instead, I tested with taking a command like `java <flags> JavaBuilder.jar <@argfiles>` and truncating the `@argsfiles` and before adding the `--persistent_worker` flag. However, this assumes that the first argument(s) of the command is an `@argsfile`, which I'm not sure is true in general, and is probably why we ended up with a `persistentWorkerCommand` requirement. Otherwise, it seems to work (i.e. `cmp -l <build-with-pw-repo>/bazel-bin/src/main/java/build/buildfarm/buildfarm-server_deploy.jar <build-with-local-repo>/bazel-bin/src/main/java/build/buildfarm/buildfarm-server_deploy.jar`).

2023-11-20 03:32 UTC, werkt commented on src/main/java/build/buildfarm/worker/persistent/PersistentExecutor.java
> +    }
I'm going to hope that the lack of JavaBuilder support means that nobody is going to expect their execution to change with any env vars across instantiation. Probably a big hope. Also its not immediately clear that this `env` only has ties to the key creation (I figured it had to do with the execution overall until looking with your update where this applies). Maybe move it down under 'Make Key' and label it as `keyEnv`?

2023-11-20 03:34 UTC, werkt commented on src/main/java/build/buildfarm/worker/BUILD
> +        "//persistentworkers/src/main/java/persistent/common:persistent-common",
I'm blind, thanks for the gut check!

2023-11-20 19:31 UTC, wiwa commented on src/main/java/build/buildfarm/worker/persistent/PersistentExecutor.java
> +    }
It is in fact tied to the execution as well as key creation. I think the reality is that these lines of code should be updated in the future after further investigation and/or bug reports. However, this was what was tested back at Twitter and from what I could tell, it was required for correct functionality. This shouldn't be taken as "lack of JavaBuilder support", but rather, this *is* JavaBuilder support.

2023-11-20 19:52 UTC, werkt approved these changes

2023-11-20 19:52 UTC, werkt commented on src/main/java/build/buildfarm/worker/persistent/PersistentExecutor.java
> +    }
What I meant on 'lack of JavaBuilder support' there was its lack of interpretation of env vars to affect its runtime - sorry if that was confusing.

And I'm not seeing the use of the env anywhere except in the call to Keymaker.make, but if you're saying that it is used somehow through injection where it affects the execution by way of the key constituency, sounds good.

2023-11-20 19:53 UTC, merged