[config] allow the sandbox to be chosen by default
bazelbuild/bazel-buildfarm pull request #1266
Opened 2023-02-17 06:28 UTC by luxe

2023-02-20 05:15 UTC, werkt requested changes
Given all the additions of SandboxSettings() here to the tests, can you add some test validation that they're behaving the way you expect in loop?

2023-02-23 05:39 UTC, luxe commented
> Given all the additions of SandboxSettings() here to the tests, can you add some test validation that they're behaving the way you expect in loop?

unit tests added!

2023-03-28 19:03 UTC, werkt commented on _site/docs/configuration/configuration.md
> +| selectForTmpFs        | boolean, _false_      | Only use the sandbox when using tmpfs.          |
The Only language here confuses me: I'd change this to something like "block-network implies actions run under sandbox", if that's the right tag.

2023-03-28 19:06 UTC, werkt commented on src/test/java/build/buildfarm/worker/resources/ResourceDeciderTest.java
> +    assertThat(limits.useLinuxSandbox).isTrue();
I want to see a negative test for this as well, where useLinuxSandbox is false for selectForBlockNetwork is true for non-network blocking platform

2023-03-28 19:07 UTC, werkt approved these changes
Approve pending comment mitigation

2023-03-28 20:10 UTC, merged