[redis] Actually respect dequeue timeout in priortyqueue dequeue
bazelbuild/bazel-buildfarm pull request #1307
Opened 2023-03-30 22:55 UTC by klimermana

The dequeue function in the RedisPriorityQueue wasn't actually waiting for the full timeout.   It was also hitting redis up to 1k evals / second in our environment.

related to #1304

2023-03-30 23:57 UTC, werkt requested changes

2023-03-30 23:57 UTC, werkt commented on src/main/java/build/buildfarm/common/redis/RedisPriorityQueue.java
> +    double pollInterval = 0.1;
Please make this into a parameter for the PriorityQueue object and inject it via a config.

2023-03-30 23:57 UTC, werkt commented on src/test/java/build/buildfarm/common/redis/RedisPriorityQueueTest.java
> +    assertThat(timeElasped).isGreaterThan((long) 1000);
typo: timeElapsed, 1000L will make the cast unnecessary

2023-03-31 14:57 UTC, luxe approved these changes

2023-04-04 03:40 UTC, werkt approved these changes
@klimermana needs a lint run for a cleanup

2023-04-04 13:11 UTC, merged