add explanation for resolving block list error
bazelbuild/bazel-buildfarm pull request #691
Opened 2021-02-25 15:39 UTC by luxe

A user hit this error message and wasn't sure what to do.  Add more context to the error message.

2021-02-25 17:06 UTC, jacobmou approved these changes
Thanks for the extra explanation!

2021-02-25 17:15 UTC, werkt requested changes

2021-02-25 17:15 UTC, werkt commented on src/main/java/build/buildfarm/instance/shard/ShardInstance.java
> +
Please present this string in the current location for error messages: https://github.com/bazelbuild/bazel-buildfarm/blob/4f0c6f595126950905e5ea625eacddc06e63cafa/src/main/java/build/buildfarm/instance/server/AbstractServerInstance.java#L145-L200, or something more pertinent for ShardInstance if you feel it is isolated enough to it. StringBuilder is not a facility to be used just for 'long' error messages.

2021-02-26 00:35 UTC, luxe commented
@werkt fixed

2021-03-05 20:29 UTC, luxe commented
@werkt bump!

2021-03-06 00:08 UTC, werkt commented
This response is very bazel specific. When users come at it with confusion over no-remote, I'll prefer a tool check before advising.

2021-03-06 00:09 UTC, werkt approved these changes

2021-03-06 00:33 UTC, luxe commented
> This response is very bazel specific. When users come at it with confusion over no-remote, I'll prefer a tool check before advising.

yes, good idea. It will be cool to see buildfarm work with non-bazel clients.  For now, this helps guide our internal colleagues.

2021-03-06 00:33 UTC, merged